### ISSUE TITLE
Class Percentage - Grade Equivalent

### ISSUE THREAD

**Issue by jessiewestlake** [luispadron/GradePoint#1]
In one of my math classes, a 92% constitutes an A, whereas 90% would equate to an A-. I believe it is at Instructor’s discretion, so one class may be different from the next. 

After entering in assignments to a weighted class on Gradepoint, my cumulative percentage was 92.5, which resulted in an A-, whereas it would have actually been an A. The app should allow some ability to adjust for that. Otherwise, it’s a pretty nice program.

p.s. I’m planning on transferring to U-M for computer science. I was surprised to see that on your profile when I clicked through from the apps settings menu.

**Comment by luispadron** [comment]
Hey!

I’m actually working on this feature right now, I’ve got most of the UI sorted out and it should be done soon, thanks for the request. 

If you have questions about Michigan and transferring like I did feel free to email me, good luck!

**Comment by luispadron** [comment]
This is now available in [5.0.0](https://github.com/luispadron/GradePoint/releases/tag/v5.0.0) will be out in the App Store for an update in a few days, thanks again for the request!
